language: c++

before_install:
    - echo "yes" | sudo add-apt-repository ppa:antumdeluge/sdl2
    - sudo apt-get update

install:
    - sudo apt-get install libsdl2 libsdl2-dev  libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

script: make

notifications:
    email: false